export const stringifiedAnimeKeys = [
  "images",
  "trailer",
  "titles",
  "aired",
  "broadcast",
  "producers",
  "licensors",
  "studios",
  "genres",
  "explicit_genres",
  "themes",
  "demographics",
  "relations",
  "theme",
  "external",
  "streaming",
];

export const animeFilters = {
  sfw: [true, false],
  status: ["airing", "completed", "upcoming"],
  type: [
    "tv",
    "movie",
    "ova",
    "special",
    "ona",
    "music",
    "cm",
    "pv",
    "tv_special",
  ],
  rating: ["g", "pg", "pg13", "r17", "r", "rx"],
  orderBy: [
    "mal_id",
    "title",
    "start_date",
    "end_date",
    "episodes",
    "score",
    "scored_by",
    "rank",
    "popularity",
    "members",
    "favorites",
  ],
  sort: ["desc", "asc"],
};
