name = "quiz-game"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-05-11"
main="src/index.ts"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "Game" ]
