name = "anime-site"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
ANIME_API = "https://api.jikan.moe/v4"
BETTER_AUTH_URL = "https://notmyanimelist.com"
EMAIL_FROM = "noreply@notmyanimelist.com"
BASE_URL= "https://anime.notmyanimelist.com"
GOOGLE_REDIRECT_URI="https://notmyanimelist.com/api/auth/callback/google"
BASE_URL="https://notmyanimelist.com"
