export const stringifiedMangaKeys = [
  "images",
  "trailer",
  "titles",
  "aired",
  "broadcast",
  "producers",
  "licensors",
  "studios",
  "genres",
  "explicit_genres",
  "themes",
  "demographics",
  "relations",
  "theme",
  "external",
  "streaming",
];

export const mangaFilters = {
  status: {
    label: "Status",
    options: [
      { label: "Airing", value: "Finished Airing" },
      { label: "Completed", value: "Currently Airing" },
      { label: "Upcoming", value: "Not yet aired" },
    ],
  },
  type: {
    label: "Type",
    options: [
      { label: "TV", value: "tv" },
      { label: "Movie", value: "movie" },
      { label: "OVA", value: "ova" },
      { label: "Special", value: "special" },
      { label: "ONA", value: "ona" },
      { label: "Music", value: "music" },
      { label: "CM", value: "cm" },
      { label: "PV", value: "pv" },
      { label: "TV Special", value: "tv_special" },
    ],
  },
  rating: {
    label: "Rating",
    options: [
      { label: "G - All Ages", value: "G - All Ages" },
      { label: "PG - Children", value: "PG - Children" },
      {
        label: "PG-13 - Teens 13 or older",
        value: "PG-13 - Teens 13 or older",
      },
      {
        label: "R - 17+ (violence & profanity)",
        value: "R - 17+ (violence & profanity)",
      },
      { label: "R+ - Mild Nudity", value: "R+ - Mild Nudity" },
      { label: "Rx - Hentai", value: "Rx - Hentai" },
    ],
  },
  genres: {
    label: "Genres",
    options: [
      { label: "Action", value: "action" },
      { label: "Adventure", value: "adventure" },
      { label: "Avant Garde", value: "avant_garde" },
      { label: "Award Winning", value: "award_winning" },
      { label: "Boys Love", value: "boys_love" },
      { label: "Comedy", value: "comedy" },
      { label: "Drama", value: "drama" },
      { label: "Fantasy", value: "fantasy" },
      { label: "Girls Love", value: "girls_love" },
      { label: "Gourmet", value: "gourmet" },
      { label: "Horror", value: "horror" },
      { label: "Mystery", value: "mystery" },
      { label: "Romance", value: "romance" },
      { label: "Sci-Fi", value: "sci_fi" },
      { label: "Slice of Life", value: "slice_of_life" },
      { label: "Sports", value: "sports" },
      { label: "Supernatural", value: "supernatural" },
      { label: "Suspense", value: "suspense" },
      { label: "Ecchi", value: "ecchi" },
      { label: "Erotica", value: "erotica" },
      { label: "Hentai", value: "hentai" },
      { label: "Adult Cast", value: "adult_cast" },
      { label: "Anthropomorphic", value: "anthropomorphic" },
      { label: "CGDCT", value: "cgdct" },
      { label: "Childcare", value: "childcare" },
      { label: "Combat Sports", value: "combat_sports" },
      { label: "Crossdressing", value: "crossdressing" },
      { label: "Delinquents", value: "delinquents" },
      { label: "Detective", value: "detective" },
      { label: "Educational", value: "educational" },
      { label: "Gag Humor", value: "gag_humor" },
      { label: "Gore", value: "gore" },
      { label: "Harem", value: "harem" },
      { label: "High Stakes Game", value: "high_stakes_game" },
      { label: "Historical", value: "historical" },
      { label: "Idols (Female)", value: "idols_female" },
      { label: "Idols (Male)", value: "idols_male" },
      { label: "Isekai", value: "isekai" },
      { label: "Iyashikei", value: "iyashikei" },
      { label: "Love Polygon", value: "love_polygon" },
      { label: "Magical Sex Shift", value: "magical_sex_shift" },
      { label: "Mahou Shoujo", value: "mahou_shoujo" },
      { label: "Martial Arts", value: "martial_arts" },
      { label: "Mecha", value: "mecha" },
      { label: "Medical", value: "medical" },
      { label: "Military", value: "military" },
      { label: "Music", value: "music" },
      { label: "Mythology", value: "mythology" },
      { label: "Organized Crime", value: "organized_crime" },
      { label: "Otaku Culture", value: "otaku_culture" },
      { label: "Parody", value: "parody" },
      { label: "Performing Arts", value: "performing_arts" },
      { label: "Pets", value: "pets" },
      { label: "Psychological", value: "psychological" },
      { label: "Racing", value: "racing" },
      { label: "Reincarnation", value: "reincarnation" },
      { label: "Reverse Harem", value: "reverse_harem" },
      { label: "Love Status Quo", value: "love_status_quo" },
      { label: "Samurai", value: "samurai" },
      { label: "School", value: "school" },
      { label: "Showbiz", value: "showbiz" },
      { label: "Space", value: "space" },
      { label: "Strategy Game", value: "strategy_game" },
      { label: "Super Power", value: "super_power" },
      { label: "Survival", value: "survival" },
      { label: "Team Sports", value: "team_sports" },
      { label: "Time Travel", value: "time_travel" },
      { label: "Vampire", value: "vampire" },
      { label: "Video Game", value: "video_game" },
      { label: "Visual Arts", value: "visual_arts" },
      { label: "Workplace", value: "workplace" },
      { label: "Urban Fantasy", value: "urban_fantasy" },
      { label: "Villainess", value: "villainess" },
      { label: "Josei", value: "josei" },
      { label: "Kids", value: "kids" },
      { label: "Seinen", value: "seinen" },
      { label: "Shoujo", value: "shoujo" },
      { label: "Shounen", value: "shounen" },
    ],
  },
  sfw: {
    label: "SFW",
    type: "radio",
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
  },
  orderBy: {
    label: "Order By",
    type: "radio",
    options: [
      { label: "Title", value: "title" },
      { label: "Start Date", value: "start_date" },
      { label: "End Date", value: "end_date" },
      { label: "Episodes", value: "episodes" },
      { label: "Score", value: "score" },
      { label: "Scored By", value: "scored_by" },
      { label: "Rank", value: "rank" },
      { label: "Popularity", value: "popularity" },
      { label: "Favorites", value: "favorites" },
    ],
  },
  sort: {
    label: "Sort",
    type: "radio",
    options: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
  },
} as const;
export type MangaFilters = typeof mangaFilters;
